# -*- coding: utf-8 -*-
"""Olympics  Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10eWUY8pKTsZDdJbWKvkmKqKBqihimuMx

# **Importing libraries &  Upload Dataset**
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df_athlete = pd.read_csv('/content/athlete_events.csv')

df_athlete

df_noc_regions = pd.read_csv("/content/noc_regions.csv")

df_noc_regions

"""# **About Dataset**

**Within a context of analyzing Olympic data, there are two CSV files in this dataset. The initial file, noc_regions.csv, has 230 entries spread across 3 columns: NOC, region and notes. In this case, the NOC column gives different National Olympic Committee (NOC) codes that represent countries or regions participating in the Olympics. Further on, the region column provides the corresponding names of regions or countries for every NOC code listed. Further still, more details contained in the notes column though only sparsely populated with just 21 non-null entries. Note that some values are missing in the region column showing that not all NOC codes have been given a name of their respective regions in this data set.**

**The second one is much larger as it comprises fifteen columns which have a total of two hundred seventy one thousand one hundred sixteen entries (271116). It captures information about individual athletes who took part in the Olympic Games with great detail. These include basic demographic attributes such as ID, Name, Sex, Age, Height and Weight; alongside records related to their participation at Olympics which consist Team; NOC; Games; Year; Season; City; Sport; Event and Medal. By far the most significant among these is the Medal column as it indicates if an athlete won a medal and what type it was if he/she did so. However**
"""

df_athlete.head()

df_noc_regions.head()

df_athlete.tail()

df_noc_regions.tail()

"""# **Data Cleaning**"""

df_athlete.isnull().sum()

df_athlete = df_athlete.dropna()

df_noc_regions = df_noc_regions.dropna()

df_noc_regions.isna().sum()

df_athlete.isna().sum()

"""# **Visualizing the Medal Distribution Across Countries ?**

* United States Top with **4273** Medals,Soviet union,Germany and Australia Russia,Canada 2nd 3rd 4th 5th represently
"""

dis_cy = df_athlete.groupby('Team')['Medal'].count().sort_values(ascending=False).reset_index().head(10)

dis_cy

plt.figure(figsize = (15,6))
sns.barplot(x= 'Team',y = "Medal",data = dis_cy,color= "Red")
plt.title("Distribution of Medals by Countries")
plt.xlabel("Countries")
plt.ylabel("Number Of Medals")
plt.show()

"""# **Visualizing Athlete Participation Across Different Sports?**
* "The barplot illustrates the number of athletes participating in each sport, highlighting the sports with the highest and lowest levels of athlete involvement.
* **athletics** most playing Gaming In Olympics,**Rowing**, **Swimming** 2nd,3rd *
"""

df_ath = df_athlete.groupby('Sport')['Name'].nunique().sort_values(ascending=False).reset_index(name = 'Number of Atheletes').head(10)

plt.figure(figsize = (15,6))
sns.barplot(x= "Sport",y = 'Number of Atheletes',data = df_ath,color= 'Red')
plt.title("Number of Althelete in Each Sport")
plt.xlabel("Number of Sports")
plt.ylabel("Number of Altheletes")
plt.show()

"""# **Visualizing the Top Countries with the Most Gold Medals ?**
* **US have dominated in achieving top podium finishes,Soviet union and Germany 2dn, 3rd**
"""

df_gold = df_athlete[df_athlete["Medal"]=='Gold']

df_gold = df_gold.groupby('Team')["Medal"].count().sort_values(ascending=False).reset_index(name = 'Number of Gold Medals').head(10)

plt.figure(figsize = (15,6))
sns.barplot(x= "Team",y = "Number of Gold Medals",data =df_gold,color = 'Red' )
plt.title("Top countries with the most Gold medals")
plt.xlabel("Countries")
plt.ylabel("Number of medals")
plt.show()

"""# **Convert the 'Year' column to a datetime object for accurate analysis of athlete data over time.**"""

df_athlete["Year"]= pd.to_datetime(df_athlete['Year'],format = "%Y").dt.year
df_athlete

"""# **Trends in Medal Counts Over the Years**
* **After 1940 Number Of Medals Repidaly increase,sunddenly Down Falls in 1999 Around**
* The line plot reveals the fluctuations in the number of medals awarded over time, indicating significant peaks and troughs in various periods.
"""

df_year = df_athlete.Year.value_counts().reset_index()
df_year.sort_values(by = 'Year').head(1)

plt.figure(figsize= (15,6))
sns.lineplot(x= 'Year',y= 'count',data = df_year)
plt.title("number of medal over time")
plt.xlabel("Year")
plt.ylabel("Medals counts")